[package]
name = "catvec"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.1"
defmac = "0.2.1"
fastrand = "1.5.0"
log = "0.4.14"
tap = "1.0.1"

[dev-dependencies]
env_logger="0.9" 